Added master param for PhotoImage object in ctkimage
This solves garbage collection problem. Especially the error:
self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
_tkinter.TclError: image "pyimage2" doesn't exist